import { TeamEmblem } from '../shared/team-emblem'
import { InquiryForm } from '../forms/inquiry-form'
import { ContactLinks } from '../shared/contact-links'
import { inquiriesConfigured } from '../../lib/supabase/admin'
import { EventGallery } from './event-gallery'
import Link from 'next/link'
import { currentEdition, editionTeams } from '../../data/current-edition'
import { players, proposedPrices, sponsorTiers, standCategories, voteCategories } from '../../data/catalog'
import { programme } from '../../data/programme'
import { formatXaf } from '../../lib/formatting'
import { CTASection, EmptyState, InfoCards, Section } from '../shared/page'
import { PlayerCard, PlayerDirectory } from './player-directory'
import { ProgrammeList } from './programme-list'
import { SponsorStrip } from '../shared/sponsor-strip'

export function PublicPageContent({ path }: { path: string }) {
  switch (path) {
    case '/programme': return <Section title="Les temps forts envisagés"><ProgrammeList items={programme.filter((item) => item.editionId === currentEdition.id)} /></Section>
    case '/players': return <Section title="Les effectifs"><PlayerDirectory players={players.filter((player) => player.editionId === currentEdition.id)} teams={editionTeams} /></Section>
    case '/teams': return <><div className="public-team-grid">{editionTeams.map((team) => { const roster = players.filter((player) => player.editionId === currentEdition.id && player.teamId === team.id && player.public); return <article className="public-team" key={team.id} style={{ '--team-accent': team.accent } as React.CSSProperties}><span className="eyebrow">ÉDITION {currentEdition.editionNumber}</span><TeamEmblem team={team.id} /><h2>{team.name}</h2><p>{roster.length} joueurs annoncés dans l’effectif.</p><Link className="text-link" href={`#squad-${team.id}`}>Voir l’effectif →</Link></article> })}</div>{editionTeams.map((team) => { const roster = players.filter((player) => player.editionId === currentEdition.id && player.teamId === team.id && player.public); return <section className="team-squad" id={`squad-${team.id}`} key={team.id} aria-labelledby={`squad-${team.id}-title`} style={{ '--team-accent': team.accent } as React.CSSProperties}><div className="team-squad-heading"><div><span className="eyebrow">{roster.length} JOUEURS</span><h2 id={`squad-${team.id}-title`}>{team.name}</h2></div><TeamEmblem team={team.id} /></div><div className="player-grid">{roster.map((player) => <PlayerCard key={player.id} player={player} team={team} />)}</div></section> })}</>
    case '/tickets': return <Section title="Billetterie ouverte"><p className="muted">Choisissez une catégorie et réservez vos billets pour le 19 décembre 2026. Le paiement se fait par Mobile Money et les billets sont délivrés après vérification du reçu par l’organisation.</p><Link className="button button-primary" href="/tickets">Choisir mes billets →</Link></Section>
    case '/vote': return <><Section title="Les distinctions envisagées"><p className="muted">Catégories prévisionnelles, à valider avant l’ouverture des campagnes.</p><div className="category-grid">{voteCategories.map((name) => <div key={name}>{name}<small>À confirmer</small></div>)}</div></Section><Section title="Comment participer ?"><InfoCards items={[{ title: 'Découvrez les candidats', description: 'Les profils éligibles et les dates seront publiés pour chaque campagne.' }, { title: 'Consultez les modalités', description: `Tarif proposé : ${formatXaf(proposedPrices.vote)} par vote. Les règles restent à confirmer.` }, { title: 'Suivez les résultats', description: 'La politique de publication sera annoncée avant l’ouverture des votes.' }]} /></Section><Link className="text-link" href="/vote/results">Résultats des campagnes →</Link></>
    case '/tombola': return <><Section title="Le principe"><InfoCards items={[{ title: 'Participation', description: `Prix proposé : ${formatXaf(proposedPrices.tombola)} par participation, à confirmer.` }, { title: 'Votre numéro', description: 'À l’ouverture, chaque participation confirmée recevra un numéro unique.' }, { title: 'Le tirage', description: 'Date, règlement et modalités de publication à annoncer avant toute participation.' }]} /></Section><Section title="Les lots"><EmptyState title="Des lots à découvrir" description="Les lots et leurs partenaires seront présentés uniquement après confirmation." /></Section><Section title="Vos questions"><details><summary>Peut-on déjà participer ?</summary><p>Non, les participations ne sont pas ouvertes.</p></details><details><summary>Quand aura lieu le tirage ?</summary><p>La date sera publiée avec le règlement officiel.</p></details><details><summary>Où seront publiés les gagnants ?</summary><p>Sur cette page, selon les modalités de confidentialité du règlement.</p></details></Section></>
    case '/sponsors': return <><SponsorStrip /><Section title="Construisons le Classico ensemble"><div className="category-grid">{sponsorTiers.map((tier) => <div key={tier}>{tier}<small>Partenaires à confirmer</small></div>)}</div></Section><CTASection title="Faites partie de l’aventure" description="Football, culture et communauté : trouvez votre place dans l’écosystème." href="/partner" label="Devenir partenaire" /></>
    case '/partner': return <><Section title="Une présence au cœur de l’expérience"><InfoCards items={[{ title: 'Sur le terrain', description: 'Explorez les possibilités de présence lors de l’événement et sur les espaces commerciaux.' }, { title: 'Dans la communauté', description: 'Associez votre organisation aux contenus et aux expériences du public.' }, { title: 'Autour des passions', description: 'Football, culture ou tombola : discutons du volet adapté à votre projet.' }]} /></Section><InquiryForm kind="partner" enabled={inquiriesConfigured()} /><Link className="button button-primary" href="/contact">Contact & informations →</Link></>
    case '/stands': return <><Section title="Réservation des stands"><p className="muted">La location est de 10 000 XAF par stand, dans la limite de 10 stands. Envoyez vos coordonnées et l’organisation vous contactera pour confirmer la disponibilité et les modalités de paiement. Aucun paiement n’est demandé avec ce formulaire.</p><InfoCards items={[{ title: 'Votre activité', description: `Catégorie : ${standCategories.join(', ')}. Indiquez le nom de votre entreprise, votre ville et les produits ou services proposés.` }, { title: 'Votre contact', description: 'Nom du responsable, téléphone camerounais et adresse e-mail.' }, { title: 'Votre installation', description: 'Type de stand souhaité, besoins techniques et message à l’organisation.' }]} /></Section><InquiryForm kind="exhibitor" enabled={inquiriesConfigured()} /><CTASection title="Une question sur votre réservation ?" description="Contactez l’équipe organisatrice pour obtenir des précisions." href="/contact" label="Nous contacter" /></>
    case '/gallery': return <Section title="Sur le terrain, dans les tribunes"><p className="muted">Une sélection des archives Classico Mboa. Les dates et éditions ne sont pas attribuées tant qu’elles ne sont pas confirmées.</p><EventGallery /></Section>
    case '/news': return <EmptyState title="Les annonces arrivent" description="Les nouvelles des équipes, des artistes et de la communauté seront publiées ici après validation." />
    case '/contact': return <><Section title="Contactez-nous directement"><p className="muted">Écrivez-nous par e-mail ou échangez avec Manoel et Youana sur WhatsApp.</p><ContactLinks /></Section><Section title="Le bon point de départ"><InfoCards items={[{ title: 'Billetterie & public', description: 'Billets, accès, programme et informations pratiques.' }, { title: 'Entreprises & partenaires', description: 'Partenariats, médias et demandes de réservation de stands de vente.' }, { title: 'Culture & communauté', description: 'Animations et participation du public.' }]} /></Section><InquiryForm kind="contact" enabled={inquiriesConfigured()} /></>
    default: return null
  }
}
