import { InquiryForm } from '../forms/inquiry-form'
import { ContactLinks } from '../shared/contact-links'
import { inquiriesConfigured } from '../../lib/supabase/admin'
import { EventGallery } from './event-gallery'
import Link from 'next/link'
import { currentEdition, editionTeams } from '../../data/current-edition'
import { players, proposedPrices, sponsorTiers, villageCategories, voteCategories } from '../../data/catalog'
import { programme } from '../../data/programme'
import { formatXaf } from '../../lib/formatting'
import { CTASection, EmptyState, InfoCards, Section } from '../shared/page'
import { PlayerDirectory } from './player-directory'
import { ProgrammeList } from './programme-list'
import { SponsorStrip } from '../shared/sponsor-strip'

export function PublicPageContent({ path }: { path: string }) {
  switch (path) {
    case '/programme': return <Section title="Les temps forts envisagés"><ProgrammeList items={programme.filter((item) => item.editionId === currentEdition.id)} /></Section>
    case '/players': return <Section title="Les effectifs"><PlayerDirectory players={players.filter((player) => player.editionId === currentEdition.id)} teams={editionTeams} /></Section>
    case '/teams': return <><div className="public-team-grid">{editionTeams.map((team) => <article className="public-team" key={team.id} style={{ '--team-accent': team.accent } as React.CSSProperties}><span className="eyebrow">ÉDITION {currentEdition.editionNumber}</span><h2>{team.name}</h2><p>Une équipe, une identité, une communauté. Effectif et encadrement à annoncer.</p><Link className="text-link" href="/players">Découvrir les joueurs →</Link></article>)}</div><EmptyState title="La rivalité s’écrit ensemble" description="Les statistiques et résultats seront publiés à partir des rencontres officielles." /></>
    case '/tickets': return <><Section title="Préparer votre venue"><p className="muted">Tarifs proposés dans le projet, soumis à confirmation. Aucun billet n’est en vente.</p><InfoCards items={[{ title: `Classique · ${formatXaf(proposedPrices.classique)}`, description: 'Catégorie prévisionnelle. Conditions d’accès à confirmer.' }, { title: `VIP · ${formatXaf(proposedPrices.vip)}`, description: 'Catégorie prévisionnelle. Avantages et capacité à confirmer.' }]} /></Section><Section title="Une billetterie pensée pour le Mboa"><InfoCards items={[{ title: 'Choisir son billet', description: 'Les catégories et quantités disponibles seront affichées à l’ouverture.' }, { title: 'Régler en FCFA', description: 'MTN Mobile Money et Orange Money sont envisagés. Les moyens disponibles seront confirmés avant les ventes.' }, { title: 'Présenter son ticket', description: 'Les modalités du billet numérique et de l’accès seront communiquées avec la billetterie.' }]} /></Section></>
    case '/vote': return <><Section title="Les distinctions envisagées"><p className="muted">Catégories prévisionnelles, à valider avant l’ouverture des campagnes.</p><div className="category-grid">{voteCategories.map((name) => <div key={name}>{name}<small>À confirmer</small></div>)}</div></Section><Section title="Comment participer ?"><InfoCards items={[{ title: 'Découvrez les candidats', description: 'Les profils éligibles et les dates seront publiés pour chaque campagne.' }, { title: 'Consultez les modalités', description: `Tarif proposé : ${formatXaf(proposedPrices.vote)} par vote. Les règles restent à confirmer.` }, { title: 'Suivez les résultats', description: 'La politique de publication sera annoncée avant l’ouverture des votes.' }]} /></Section><Link className="text-link" href="/vote/results">Résultats des campagnes →</Link></>
    case '/tombola': return <><Section title="Le principe"><InfoCards items={[{ title: 'Participation', description: `Prix proposé : ${formatXaf(proposedPrices.tombola)} par participation, à confirmer.` }, { title: 'Votre numéro', description: 'À l’ouverture, chaque participation confirmée recevra un numéro unique.' }, { title: 'Le tirage', description: 'Date, règlement et modalités de publication à annoncer avant toute participation.' }]} /></Section><Section title="Les lots"><EmptyState title="Des lots à découvrir" description="Les lots et leurs partenaires seront présentés uniquement après confirmation." /></Section><Section title="Vos questions"><details><summary>Peut-on déjà participer ?</summary><p>Non, les participations ne sont pas ouvertes.</p></details><details><summary>Quand aura lieu le tirage ?</summary><p>La date sera publiée avec le règlement officiel.</p></details><details><summary>Où seront publiés les gagnants ?</summary><p>Sur cette page, selon les modalités de confidentialité du règlement.</p></details></Section></>
    case '/village': return <><Section title="Le Mboa a du talent"><p>Un espace pour découvrir les entreprises, créateurs et saveurs de notre communauté.</p><div className="category-grid">{villageCategories.map((category) => <div key={category}>{category}</div>)}</div></Section><EmptyState title="Les exposants se préparent" description="L’annuaire et le plan du Village seront publiés après sélection des exposants et attribution des emplacements." /><CTASection title="Votre activité au Village" description="Découvrez comment préparer votre candidature." href="/stands" label="Devenir exposant" /></>
    case '/sponsors': return <><SponsorStrip /><Section title="Construisons le Classico ensemble"><div className="category-grid">{sponsorTiers.map((tier) => <div key={tier}>{tier}<small>Partenaires à confirmer</small></div>)}</div></Section><CTASection title="Faites partie de l’aventure" description="Football, culture et communauté : trouvez votre place dans l’écosystème." href="/partner" label="Devenir partenaire" /></>
    case '/partner': return <><Section title="Une présence au cœur de l’expérience"><InfoCards items={[{ title: 'Sur le terrain', description: 'Explorez les possibilités de présence lors de l’événement et au Village.' }, { title: 'Dans la communauté', description: 'Associez votre organisation aux contenus et aux expériences du public.' }, { title: 'Autour des passions', description: 'Football, culture ou tombola : discutons du volet adapté à votre projet.' }]} /></Section><InquiryForm kind="partner" enabled={inquiriesConfigured()} /><Link className="button button-primary" href="/contact">Contact & informations →</Link></>
    case '/stands': return <><Section title="Préparez votre candidature"><InfoCards items={[{ title: 'Votre activité', description: 'Nom de l’entreprise, catégorie, ville et présentation des produits ou services.' }, { title: 'Votre contact', description: 'Nom du responsable, téléphone camerounais et adresse e-mail.' }, { title: 'Votre installation', description: 'Type de stand souhaité, besoins techniques et message à l’organisation.' }]} /></Section><InquiryForm kind="exhibitor" enabled={inquiriesConfigured()} /><CTASection title="Découvrir l’esprit du Village" description="Un espace pour les commerces, les créateurs et les services." href="/village" label="Explorer le Village" /></>
    case '/gallery': return <Section title="Sur le terrain, dans les tribunes"><p className="muted">Une sélection des archives Classico Mboa. Les dates et éditions ne sont pas attribuées tant qu’elles ne sont pas confirmées.</p><EventGallery /></Section>
    case '/news': return <EmptyState title="Les annonces arrivent" description="Les nouvelles des équipes, des artistes et de la communauté seront publiées ici après validation." />
    case '/contact': return <><Section title="Contactez-nous directement"><p className="muted">Écrivez-nous par e-mail ou échangez avec Manuel et Youana sur WhatsApp.</p><ContactLinks /></Section><Section title="Le bon point de départ"><InfoCards items={[{ title: 'Billetterie & public', description: 'Billets, accès, programme et informations pratiques.' }, { title: 'Entreprises & partenaires', description: 'Partenariats, médias et demandes d’exposition au Village.' }, { title: 'Culture & communauté', description: 'Animations et participation du public.' }]} /></Section><InquiryForm kind="contact" enabled={inquiriesConfigured()} /></>
    default: return null
  }
}
